name: dart_segment_fault
description: demo bug segment fault

environment:  
  sdk: '>=2.18.0 < 3.0.0'

dependencies: 
  angel3_framework: ^7.0.0  
  angel3_auth: ^7.0.0
  angel3_configuration: any  
  angel3_jael: any
  angel3_production: any
  angel3_static: any
  angel3_validate: any
  angel3_cors: any
  belatuk_pretty_logging: any
  uuid: any
  dotenv: any
  intl: any
  http:  any
  path: any
  jaguar_jwt: any
  crypto: any
  xml: any
  csslib: any
  # para assinar PDF
  dart_pdf:
   git:
    url: https://github.com/insinfo/insinfo_dart_pdf
    ref: main    #branch name  
  asn1lib: any
  pointycastle: any
  basic_utils: any
  image: any  
  convert: any

  #eloquent: 
    #path: ../../eloquent  
    
  #eloquent:
   #git:
      #ref: main
      #url: https://github.com/insinfo/eloquent_dart.git     
  eloquent: ^2.1.2

  new_sali_core:
    path: ../new_sali/core
  # para monitoramento com o prometheus e grafana
  prometheus_client: any  
  # shelf é usado no backend publico
  shelf: any #^1.3.0
  shelf_router: any #^1.1.2
  shelf_plus: any #1.7.0
  shelf_cors_headers: any #1.7.0 
  prometheus_client_shelf: any
  # para doc 
  shelf_swagger_ui: any
  ffi: any

dev_dependencies: 
  angel3_hot: any
  angel3_test: any
  test: any
  # para test de UI
  puppeteer: 2.23.0
 